apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-secret
  labels:
    acme.org/owned-by: "q-team"
  annotations:
    acme.org/sha: 1234

# spec:
#   refreshPolicy: OnChange
#   target: 
#     name: my-secret
#     creationPolicy: Owner
#     deletionPolicy: Retain
#     template:
#       type: kubernetes.io/dockerconfigjson



spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  target:
    name: my-app-k8s-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: my-app/db-password

