apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: github
  namespace: external-secrets
annotations:
  ## Add this annotation to disable controller warning events for unmaintained stores
  external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    github:
      appID: "<GITHUB_APP_ID>"
      installationID: "<INSTALLATION_ID>"
      organization: "<GITHUB_ORG_NAME>"
      auth:
        privateKey:
          name: github-app-private-key
          key: privateKey.pem
