apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kirkos22222
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: featdasdsad
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
