replicaCount: 1

image:
  repository: docker.io/library/nginx
  version: 1.28-alpine-perl
  pullPolicy: IfNotPresent

service:
  type: NodePort
  internalPort: 80
  externalPort: 8082

# nodig of niet?
external-secrets:
  installCRDs: true
  # andere configuratie
